### Create a new report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 2022,
  "price": 136000,
  "mileage": 24000,
  "lng": 0,
  "lat": 0
}

### Approve an existing report

PATCH http://localhost:3000/reports/cfb9b9ef-85d0-496e-9da4-85b1be737fe9	
Content-Type: application/json

{
  "approved": true
}

### Approve an existing report

GET http://localhost:3000/reports/?make=Toyota&model=Corolla&lat=0&lng=0&year=2022&mileage=24000	
Content-Type: application/json
