### Create a new report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 2022,
  "price": 136000,
  "mileage": 24000,
  "lng": 0,
  "lat": 0
}